#cat-tool.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cat-tool-config
  namespace: default
data:
  DEV_MODE: "false"
  RELATIVE_HOST_NAME: https://nltp.is/api/mc/
  STORAGE_DIR: "/data"
  CAT_DB_HOST: "nltp-database.cbwgexdrojxl.eu-west-1.rds.amazonaws.com"
  CAT_DB_NAME: "nltp_cattool"
  CAT_LOG_DB_NAME: "nltp_cattool_conversions_log"
  CAT_ACTIVEMQ_HOST: "cat-tool-activemq"
  CAT_REDIS_HOST: "cat-tool-redis"
  CAT_FILTERS_HOST: "cat-tool-filters"
  FILE_CONVERTER_BASE_URL: "http://file-converter-service/"
  MATECAT_HOST: http://localhost
  MT_BASE_URL: "https://nltp.is"
  TM_BASE_URL: "http://cat-tool-tm-service/"
  DOCUMENT_WHITELIST: "docx,xlsx,pptx,odt,odp,ods,txt"
  ALLOW_CORS: "true"
  CORS_WHITELIST: "https://nltp.is"
  TM_BLACKLIST: "public"
---
#frontend-cms.yaml configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-cms-config
  namespace: default
data:
  DATABASE_CLIENT: "mysql"
  DATABASE_HOST: "nltp-database.cbwgexdrojxl.eu-west-1.rds.amazonaws.com"
  DATABASE_NAME: "nltp_cms"
  DATABASE_PORT: "3306"
---
#common-config
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
  namespace: default
data:
  SERVICE_BASE_URL: "https://nltp.is"
  PUBLIC_CLIENT_ID: "NLTP"
  JWT_KEY_KEYCLOAK: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3LxqzG98Zqwe0SOaI3uoxdEiivyzCsN+TsbQdlN3rnahxaff4muGw0ujQtAfKxvpwJBp7IQcYHNrnrWAG2yivD/3saZGlV+/PBtJXc58GkmiSvQdRIX36VXUMMrc7Evlkm7xQ/b/YfQT/DUpBi9m2Mrgdr5P1bQuZU2IQqyJOwhFL9Oqw5Y1QkDR/0gaVYZ3RnOq2xZywhED4spvrRPhRRFvaqPeb/r3hoarZ3ufPDF6LTk/5e0WGWqNwZhAys3fvwyt/0LDHEL5/4lNmwh8lH74g/pBRA5OaxR+Bn+xbRVIWGTJ6JJsv8385VianFv75mmYq9JnB6U7Wu1s+arkMQIDAQAB"
  JWT_ISSUER_KEYCLOAK: "https://nltp-auth.nltp.is/auth/realms/Main"
  TRANSLATE_API_PUB_URI: "https://nltp.is/api/translate"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: databases
  namespace: default
data:
  filetranslation_db_host: "nltp-database.cbwgexdrojxl.eu-west-1.rds.amazonaws.com"
  filetranslation_db: "nltp_filetranslation"
  websitetranslation_db_host: "nltp-database.cbwgexdrojxl.eu-west-1.rds.amazonaws.com"
  websitetranslation_db: "nltp_websitetranslation"
---
#frontend.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: default
data:
  CAT_SERVICE_URL: "https://nltp.is/api/cat/"
  CAT_SYSTEM_LIST_URL: "https://nltp.is/api/translate/language-directions"
  CAT_TERM_LOOKUP_URL: "https://eurotermbank.com/search/{term}/{srcLang}?target={trgLang}"
  MT_APP_ID: "MT|Web|NLTP"
  KEYCLOAK_AUTH_URL: "https://nltp-auth.nltp.is/auth/"
  KEYCLOAK_REALM: "Main"
  STRAPI_API_URL: "https://nltp-cms.nltp.is"
  SUPPORT_EMAIL: "nltp-support@nltp.is"
  WT_WIDGET_URL: "https://nltp-cdn.nltp.is/latest/widget.js"
---
#keycloak.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: default
data:
  KC_HOSTNAME: "nltp-auth.nltp.is"
  KC_PRIVACY_URL: "https://nltp.is/page/privacy-policy"
  KC_TERMS_URL: "https://nltp.is/page/terms"
  DB_VENDOR: "mysql"
  DB_URL: "jdbc:mysql://nltp-database.cbwgexdrojxl.eu-west-1.rds.amazonaws.com/nltp_keycloak?characterEncoding=UTF-8&connectTimeout=30000&socketTimeout=30000&useLegacyDatetimeCode=false&serverTimezone=UTC"
---
#docs.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: docs-config
  namespace: default
data:
  TITLE: 'National Language Technology Platform'  # TODO - CHANGE THIS TO THE ICELANDIC NAME OF THE PLATFORM, DO THIS LATER BECAUSE AN ICELANDIC NAME HASN'T BEEN CHOSEN
  TAGLINE: 'National Language Technology Platform'  # TODO - NO ICELANDIC NAME HAS BEEN CHOSEN, DO THIS LATER
  URL: https://nltp.is/
  BASE_URL: /docs/
  FOOTER: "© 2022 NLTP. Allur réttur áskilinn." # TODO - DONE 
  NLTP_HOME_URL: https://nltp.is/
  NLTP_LOGO_URL: https://nltp.is/assets/images/nltp/menu-logo.svg

---
#access-management-service.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: access-management-service
  namespace: default
data:
  Services__KeyCloak__Url: "https://nltp-auth.nltp.is/"
  Services__KeyCloak__Realm: "Main"
---
#service-broker.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-broker
  namespace: default
data:
  Settings__PublicUrl: "https://nltp.is/api"
