apiVersion: v1
kind: Service
metadata:
  name: translation-system
spec:
  ports:
    - name: http
      protocol: "TCP"
      port: 80
      targetPort: 80
  selector:
    app: translation-system-api
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: translation-system-api
spec:
  selector:
    matchLabels:
      app: translation-system-api
  template:
    metadata:
      labels:
        app: translation-system-api
    spec:
      containers:
        - name: translation-system-api
          image: nltpcontainers.azurecr.io/translation-system-service:46912
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
          env:
          # System service
          - name: Services__System__Username
            valueFrom:
              secretKeyRef:
                key: system_import_username
                name: translation-services
          - name: Services__System__Password
            valueFrom:
              secretKeyRef:
                key: system_import_password
                name: translation-services
          # Database
          - name: Services__Database__ConnectionString
            valueFrom:
              secretKeyRef:
                key: systems_db_connection_string
                name: translation-services
          - name: Services__ETranslation__UserName
            valueFrom:
              secretKeyRef:
                key: etranslation_username
                name: translation-services
          - name: Services__ETranslation__Password
            valueFrom:
              secretKeyRef:
                key: etranslation_password
                name: translation-services
          livenessProbe:
            httpGet:
              path: /health/live
              port: 80
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 80
            initialDelaySeconds: 10
          resources:
            requests:
              cpu: "10m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
      imagePullSecrets:
        - name: nltp-cr-pull-secret